# Ade_shield_app_demo-*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lgDqGUkYjjSXMelXU7E8iHmtTQQy1j09
"""

import streamlit as st
import pandas as pd
import altair as alt

# -----------------------------
# CORE MODELING LOGIC (CLINICAL DETAIL + DEMOGRAPHICS)
# -----------------------------

def calculate_bleeding_risk(age, inr, anticoagulant, gi_bleed, high_bp, antiplatelet_use, gender, weight):
    """Predicts bleeding risk, factoring in underlying conditions and patient demographics."""
    score = 0

    # Acute / Drug Factors
    score += 35 if anticoagulant else 0
    score += 40 if inr > 3.5 else 0
    score += 30 if gi_bleed else 0
    score += 15 if antiplatelet_use else 0

    # Chronic / Management / Demographics Factors
    score += 10 if age > 70 else 0
    score += 10 if high_bp else 0
    score += 5 if gender == 'Female' else 0 # Small risk difference
    score += 15 if weight > 120 or weight < 50 else 0 # Extreme weight increases complexity/dosing risk

    return min(score, 100)

def calculate_hypoglycemia_risk(insulin_use, renal_status, high_hba1c, neuropathy_history, gender, weight):
    """Predicts low blood sugar risk, factoring in diabetes control status and weight."""
    score = 0

    # Acute / Drug Factors
    score += 30 if insulin_use else 0
    score += 45 if renal_status else 0

    # Chronic / Management / Demographics Factors
    score += 20 if high_hba1c else 0
    score += 10 if neuropathy_history else 0
    score += 10 if weight < 60 else 0 # Lower body weight increases sensitivity to insulin

    return min(score, 100)

def calculate_aki_risk(age, diuretic_use, acei_arb_use, high_bp, active_chemo, gender, weight):
    """Predicts Acute Kidney Injury (AKI) risk from drug classes and co-existing conditions."""
    score = 0

    # Acute / Drug Factors
    score += 30 if diuretic_use else 0
    score += 40 if acei_arb_use else 0

    # Chronic / Management / Demographics Factors
    score += 20 if age > 75 else 0
    score += 10 if high_bp else 0
    score += 20 if active_chemo else 0

    return min(score, 100)

# -----------------------------
# SIMPLE CHATBOT & INTERACTIONS
# -----------------------------
def chatbot_response(text):
    text = text.lower()
    responses = {
        # --- Core ADE Risks ---
        "warfarin": "Warfarin interacts with several medications and increases bleeding risk.",
        "amiodarone": "Amiodarone can elevate INR when combined with Warfarin.",
        "aki": "Acute Kidney Injury risk is elevated by certain blood pressure medications (ACEi/ARBs) and diuretics.",
        "metformin": "Metformin is a first-line diabetes drug but is strictly avoided in severe kidney impairment.",
        "acei": "ACE inhibitors are critical for hypertension but increase the risk of AKI, especially when combined with diuretics.",
        "doac": "Direct Oral Anticoagulants (like Apixaban) are used for clotting, but their dose must be adjusted for impaired renal function.",
        "statin": "Statins are used for cardiovascular risk reduction, but monitoring is required for severe muscle pain (myopathy).",
        "diuretic": "Diuretics are used for fluid retention but increase the risk of dehydration and electrolyte imbalances (like low potassium).",
        "sulfonylurea": "Sulfonylureas stimulate insulin release and have a high risk of causing severe hypoglycemia.",
        "diabetes": "Diabetes requires strict blood sugar monitoring; poor control (high HbA1c) increases hypoglycemia risk.",
        "hypertension": "Uncontrolled hypertension increases cardiovascular risk and stresses kidney function.",
        "cancer": "Active chemotherapy treatment increases the risk of AKI and immune suppression.",
    }
    for key in responses:
        if key in text:
            return responses[key]
    return "I need more specific clinical context. Please refine your query using drug classifications, risk factors, or one of the major ADE categories (Bleeding, Hypoglycemia, AKI)."

# -----------------------------
# DRUG INTERACTIONS 
# -----------------------------
interaction_db = {
    # --- Existing and Core Bleeding Risks ---
    ("warfarin", "amiodarone"): "Major: Amiodarone increases INR, high bleeding risk.",
    ("warfarin", "ibuprofen"): "Major: NSAIDs increase bleeding risk with Warfarin.",
    ("apixaban", "ibuprofen"): "Moderate: NSAIDs increase bleeding risk with Apixaban.",
    ("clopidogrel", "aspirin"): "Moderate: Dual antiplatelet therapy, increases bleed risk.",
    ("furosemide", "lisinopril"): "Major: Diuretic + ACEi causes severe hypotension and AKI risk.",
    ("rivaroxaban", "fluconazole"): "Major: Fluconazole increases Rivaroxaban levels (CYP3A4 inhibitor); high bleeding risk.",
    ("amlodipine", "simvastatin"): "Moderate: Amlodipine increases Simvastatin levels; increased risk of rhabdomyolysis (muscle damage).",
    ("trimethoprim/sulfamethoxazole", "metformin"): "Major: TMP/SMX increases Metformin levels, high hypoglycemia risk.",
    ("losartan", "spironolactone"): "Major: Both conserve potassium (Hyperkalemia risk), especially in renal impairment.",
    ("warfarin", "levofloxacin"): "Major: Fluoroquinolones potentiate Warfarin, extreme bleeding risk.",
    ("lisinopril", "spironolactone"): "Major: Risk of severe hyperkalemia (high potassium).",
    ("ibuprofen", "lisinopril"): "Major: Severe AKI risk (Triple Whammy component).",
    ("glipizide", "alcohol"): "Major: Increased risk of severe hypoglycemia.",
    ("metformin", "cimetidine"): "Moderate: Cimetidine increases Metformin levels, raising hypoglycemia risk.",
    ("furosemide", "vancomycin"): "Moderate: Increased risk of ototoxicity and AKI.",
}

def check_interaction(drug1, drug2):
    d1, d2 = drug1.lower().strip(), drug2.lower().strip()
    if (d1, d2) in interaction_db:
        return interaction_db[(d1, d2)]
    if (d2, d1) in interaction_db:
        return interaction_db[(d2, d1)]
    return "No major interaction found."


# -----------------------------
# Page Setup & Navigation
# -----------------------------
st.set_page_config(page_title="ADE Shield", layout="wide")
st.sidebar.title("ADE Shield Menu")

menu = st.sidebar.selectbox(
    "Select Tool",
    ["Live Dashboard", "Risk Calculator", "CSV Upload", "Medication Checker", "Chatbot"]
)

st.title("ADE Shield – Clinical Support Dashboard")

# ---------------------------------------------------
# PAGE 0 – LIVE DASHBOARD (The Split Screen View - UNMODIFIED)
# ---------------------------------------------------
if menu == "Live Dashboard":

    st.subheader("General Patient Risk Overview")

    # Displaying the general risk scores (Visuals based on the new logic)
    col_metrics = st.columns(3)
    col_metrics[0].metric("Bleeding Risk (High Alert)", "95%", "CRITICAL")
    col_metrics[1].metric("Hypoglycemia Risk", "75%", "HIGH")
    col_metrics[2].metric("AKI Risk (Renal)", "50%", "MED")

    st.markdown("---")

    # Split Layout (30% Left, 70% Right)
    col_left, col_right = st.columns([3, 7])

    # --- LEFT COLUMN: THE "INBOX" (Patient Queue) ---
    with col_left:
        st.subheader("⚠️ Patient Queue")
        st.markdown("---")

        # 1. Critical Patient (Selected) - Changed to a generalized high risk
        st.markdown('<div style="background-color:#B30000; color:white; padding:10px; border-radius:5px;">'
                    '**Patient A** (Room 302)<br>'
                    '🔴 **Risk: 95% (CRITICAL)**<br>'
                    '*Issue: Bleeding Risk*</div>',
                    unsafe_allow_html=True)

        # 2. High Risk Patient (Hypoglycemia)
        st.markdown('<div style="background-color:#FF8C00; color:black; padding:10px; border-radius:5px;">'
                    '**Patient B** (Room 410)<br>'
                    '🟠 **Risk: 75% (HIGH)**<br>'
                    '*Issue: Hypoglycemia Risk*</div>',
                    unsafe_allow_html=True)

        # 3. Low Risk Patient
        st.markdown('<div style="background-color:#D0F0C0; padding:10px; border-radius:5px; color:black;">' + '**Patient C** (Room 105)<br>'
                    '🟢 **Risk: 22% (LOW)**<br>'
                    '*Issue: Stable / Monitoring*',
                    unsafe_allow_html=True)


    # --- RIGHT COLUMN: THE "DEEP DIVE" (Analysis for Patient A) ---
    with col_right:
        # Header Zone
        st.subheader("Analysis: Patient A (78M)")
        st.caption("Risk Factors: Uncontrolled Hypertension, Active Antiplatelet Use")

        # The Big Score
        metric_col1, metric_col2 = st.columns([2, 4])
        with metric_col1:
            st.metric(label="Bleeding Risk Probability", value="95%", delta="CRITICAL")
        with metric_col2:
            st.markdown("#### 🚨 Primary Risk: Major Bleeding Event")
            st.markdown("Prediction window: Next 48 Hours")

        st.markdown("---")

        # The AI "Brain" (Feature Importance Chart - Now Comorbidity Aware)
        st.subheader("🔍 Why did the AI flag this?")
        st.caption("Top factors contributing to this risk score (Mockup of XGBoost Feature Importance)")

        # Creating dummy data for the chart visualization 
        risk_data = pd.DataFrame({
            'Risk Factor': ['Anticoagulant Use', 'High INR (>3.5)', 'Active Antiplatelet Use', 'Uncontrolled HTN'],
            'Contribution': [30, 25, 20, 15]
        })

        # Horizontal Bar Chart using Altair
        chart = alt.Chart(risk_data).mark_bar(color='#ff4b4b').encode(
            x='Contribution',
            y=alt.Y('Risk Factor', sort='-x'),
            tooltip=['Risk Factor', 'Contribution']
        ).properties(height=200)

        st.altair_chart(chart, use_container_width=True)

        st.markdown("---")

        # The Clinical Evidence
        st.subheader("📋 Live Clinical Context")

        evidence_col1, evidence_col2 = st.columns(2)
        with evidence_col1:
            st.markdown("**Active Medications:**")
            st.markdown("- **Warfarin 5mg** (Active)")
            st.markdown("- **Aspirin 81mg** (New Antiplatelet)")

        with evidence_col2:
            st.markdown("**Relevant Labs (Last 4 hrs):**")
            st.markdown("- **INR:** 4.1 (High) 🔺")
            st.markdown("- **BP:** 155/95 (Uncontrolled)")

        st.markdown("---")

        # Action Buttons
        st.subheader("Recommended Action")
        st.info("💡 Recommendation: Hold Warfarin dose. Review new Antiplatelet order due to high Bleeding Risk.")

        st.button("✅ Approve Intervention", type="primary")
        st.button("❌ Snooze Alert")

# ---------------------------------------------------
# PAGE 1 – Risk Calculator 
# ---------------------------------------------------
elif menu == "Risk Calculator":
    st.subheader("Manual Multiple-Risk Calculator (High-Detail)")
    st.caption("Adjust the patient factors below to see the predicted risk scores for multiple ADEs.")

    # --- DEMOGRAPHIC & CORE INPUTS ---
    st.markdown("#### 👤 Patient Demographics & Core Factors")

    demo_col1, demo_col2, demo_col3 = st.columns(3)
    age_calc = demo_col1.number_input("Age", 18, 100, 78)
    weight_calc = demo_col2.number_input("Weight (kg)", 30, 150, 80)
    gender_calc = demo_col3.selectbox("Gender", ['Male', 'Female'], index=0)
    inr_calc = demo_col1.number_input("INR (if applicable)", 0.5, 10.0, 4.1, format="%.2f")

    st.markdown("---")

    # --- ACUTE & CHRONIC INPUTS ---
    input_col1, input_col2, input_col3 = st.columns(3)

    # Column 1: Bleeding & GI Factors
    st.markdown("#### 🩸 Bleeding & GI Factors")
    on_anticoag = input_col1.checkbox("Anticoagulant Use", value=True)
    hist_gi_bleed = input_col1.checkbox("History of GI Bleed", value=True)
    on_antiplatelet = input_col1.checkbox("Antiplatelet Use (Aspirin/Plavix)")


    # Column 2: Diabetes & Renal Factors
    st.markdown("#### 🦠 Diabetes & Renal Factors")
    on_insulin = input_col2.checkbox("Insulin/High-Risk DM Meds", value=False)
    high_hba1c = input_col2.checkbox("HbA1c > 9.0% (Poor DM Control)", value=True)
    neuropathy_history = input_col2.checkbox("History of Neuropathy/Ulcer", value=False)
    impaired_renal = input_col2.checkbox("Impaired Renal Status", value=True)


    # Column 3: Cardiovascular & Cancer Factors
    st.markdown("#### ❤️ Cardio & Other Risks")
    uncontrolled_bp = input_col3.checkbox("Uncontrolled BP (Systolic > 140)", value=False)
    on_acei_arb = input_col3.checkbox("ACEi/ARB Therapy", value=False)
    on_diuretic = input_col3.checkbox("Diuretic Use", value=False)
    active_chemo = input_col3.checkbox("Active Chemotherapy", value=False)

    # --- CALCULATIONS ---
    # Passing new demographic factors to the calculation functions
    bleeding_risk = calculate_bleeding_risk(age_calc, inr_calc, on_anticoag, hist_gi_bleed, uncontrolled_bp, on_antiplatelet, gender_calc, weight_calc)
    hypoglycemia_risk = calculate_hypoglycemia_risk(on_insulin, impaired_renal, high_hba1c, neuropathy_history, gender_calc, weight_calc)
    aki_risk = calculate_aki_risk(age_calc, on_diuretic, on_acei_arb, uncontrolled_bp, active_chemo, gender_calc, weight_calc)

    st.markdown("---")

    # --- OUTPUTS ---
    output_col1, output_col2, output_col3 = st.columns(3)
    output_col1.metric("Bleeding Risk", f"{bleeding_risk}%", "HIGH ALERT")
    output_col2.metric("Hypoglycemia Risk", f"{hypoglycemia_risk}%", "MED ALERT")
    output_col3.metric("AKI Risk (Renal)", f"{aki_risk}%", "LOW ALERT")


    if bleeding_risk >= 70 or hypoglycemia_risk >= 70 or aki_risk >= 70:
        st.error("🚨 HIGH RISK ALERT: Check specific patient risks.")
    else:
        st.success("Patient risk is manageable. Monitoring is sufficient.")


# ---------------------------------------------------
# PAGE 2 – CSV Upload (Bulk Analysis - NOTE: Needs external CSV for testing)
# ---------------------------------------------------
elif menu == "CSV Upload":
    st.subheader("Bulk Patient Risk Analysis")

    st.markdown("Upload a CSV file with columns for all relevant factors.")
    st.info("NOTE: CSV must include all factor flags (e.g., `age`, `inr`, `gender`, `weight`, `on_antiplatelet`, `high_hba1c`, `active_chemo`, etc. as 1=Yes, 0=No).")

    uploaded = st.file_uploader("Upload CSV File", type="csv")

    if uploaded:
        df = pd.read_csv(uploaded)

        # The CSV upload is now very complex due to many required columns.
        # We will skip the full recalculation here for demo stability.
        st.warning("Bulk analysis is highly complex and requires all 15+ input columns in the CSV file for proper calculation.")
        st.dataframe(df.head())


# ---------------------------------------------------
# PAGE 3 – Medication Checker 
# ---------------------------------------------------
elif menu == "Medication Checker":
    st.subheader("Drug-Drug Interaction Checker")
    st.caption("Demo: Tests interactions against a small, hard-coded database.")

    d1 = st.text_input("Drug 1 (e.g., Warfarin)")
    d2 = st.text_input("Drug 2 (e.g., Amiodarone)")

    if d1 and d2:
        interaction = check_interaction(d1, d2)
        if "Major" in interaction:
            st.error(f"Interaction Result: {interaction}")
        elif "Moderate" in interaction:
            st.warning(f"Interaction Result: {interaction}")
        else:
            st.success(f"Interaction Result: {interaction}")


# ---------------------------------------------------
# PAGE 4 – Chatbot 
# ---------------------------------------------------
elif menu == "Chatbot":
    st.subheader("Clinical Information Chatbot")
    st.caption("Ask quick questions about the data and model logic (e.g., 'What about bleeding risk?').")

    user_input = st.text_input("Ask a question:")

    if user_input:
        response = chatbot_response(user_input)
        st.info(response)
